// Mocks generated by Mockito 5.0.9 from annotations
// in find_skill/test/features/onboarding/data/repositories/language_list_repo_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:connectivity/connectivity.dart' as _i5;
import 'package:find_skill/core/network/network_info.dart' as _i9;
import 'package:find_skill/core/services/services.dart' as _i2;
import 'package:find_skill/features/onboarding/data/datasources/language_list_local_data_source.dart'
    as _i8;
import 'package:find_skill/features/onboarding/data/datasources/language_list_remote_data_source.dart'
    as _i6;
import 'package:find_skill/features/onboarding/data/models/languages_list_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeRestClient extends _i1.Fake implements _i2.RestClient {}

class _FakeLanguagesListModel extends _i1.Fake
    implements _i3.LanguagesListModel {}

class _FakeSharedPreferences extends _i1.Fake implements _i4.SharedPreferences {
}

class _FakeConnectivity extends _i1.Fake implements _i5.Connectivity {}

/// A class which mocks [LanguagesListRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguagesListRemoteDataSource extends _i1.Mock
    implements _i6.LanguagesListRemoteDataSource {
  MockLanguagesListRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestClient get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeRestClient()) as _i2.RestClient);
  @override
  _i7.Future<_i3.LanguagesListModel> getLanguages() => (super.noSuchMethod(
          Invocation.method(#getLanguages, []),
          returnValue:
              Future<_i3.LanguagesListModel>.value(_FakeLanguagesListModel()))
      as _i7.Future<_i3.LanguagesListModel>);
}

/// A class which mocks [LanguagesListLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguagesListLocalDataSource extends _i1.Mock
    implements _i8.LanguagesListLocalDataSource {
  MockLanguagesListLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(Invocation.getter(#sharedPreferences),
          returnValue: _FakeSharedPreferences()) as _i4.SharedPreferences);
  @override
  _i7.Future<_i3.LanguagesListModel> getLastLanguages() => (super.noSuchMethod(
          Invocation.method(#getLastLanguages, []),
          returnValue:
              Future<_i3.LanguagesListModel>.value(_FakeLanguagesListModel()))
      as _i7.Future<_i3.LanguagesListModel>);
  @override
  _i7.Future<void> cacheLanguages(_i3.LanguagesListModel? languagesToCache) =>
      (super.noSuchMethod(
          Invocation.method(#cacheLanguages, [languagesToCache]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i7.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Connectivity get connectivity =>
      (super.noSuchMethod(Invocation.getter(#connectivity),
          returnValue: _FakeConnectivity()) as _i5.Connectivity);
  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
}
