name: find_skill
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  auto_route: ^2.2.0
  camera: ^0.8.1+1
  cloud_firestore: ^2.2.1
  connectivity: ^3.0.6
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6 # TODO: iOS Platform Integration
  flutter_riverpod: ^0.14.0+3
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  geocoding: ^2.0.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.1
  location: ^4.2.0
  logging: ^1.0.1
  pinput: ^1.2.0
  responsive_sizer: ^2.0.1
  retrofit: ^2.0.0
  riverpod: ^0.14.0+3
  shared_preferences: ^2.0.6
  video_player: ^2.1.1
  video_trimmer: ^0.5.1

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  chopper_generator: ^4.0.1
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mockito: ^5.0.9
  retrofit_generator: ^2.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/jpg/onboard1.jpg
    - assets/png/FindSkill-Logo-Symbol.png
    - assets/png/FindSkill-Logo-WithText.png
    - assets/png/FindSkill-Logo.png
    - assets/video/Onboarding.mp4
    - assets/video/FindSkill-English-Intro.mp4
    - assets/video/FindSkill-Hindi-Intro.mp4
    - assets/video/FindSkill-English-Notice.mp4
    - assets/video/FindSkill-Hindi-Notice.mp4
    - assets/svg/onboarding-image.svg
    - assets/svg/findskill-appbar.svg
    - assets/svg/under-construction.svg
    - lang/en.json
    - lang/hi.json

  # fonts: TODO: Check with Cristus about replacing Frutiger with one from Google Fonts
  #   - family: Fruitger-Lt
  #     fonts:
  #       - asset: assets/fonts/Frutiger-Lt/Frutiger LT 45 Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Frutiger-Lt/Frutiger LT 55 Roman.ttf
  #         style: normal
  #       - asset: assets/fonts/Frutiger-Lt/Frutiger LT 65 Bold.ttf
  #         weight: 700
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
  #         style: normal
