name: findskill
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+3

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  argon_buttons_flutter: ^1.1.0
  auto_route: ^2.2.0
  camera: ^0.8.1+7
  cloud_firestore: ^2.4.0
  connectivity: ^3.0.6
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_storage: ^10.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  flutter_spinkit: ^5.0.0
  freezed_annotation: ^0.14.2
  geocoding: ^2.0.0
  google_fonts: ^2.1.0
  hidden_drawer_menu: ^3.0.0
  image_picker: ^0.8.3+2
  # intl_phone_field: ^2.0.1
  json_annotation: ^4.1.0
  location: ^4.3.0
  logging: ^1.0.1
  pinput: ^1.2.0
  responsive_sizer: ^3.0.4+4
  retrofit: ^2.0.0
  riverpod: ^0.14.0+3
  shared_preferences: ^2.0.6
  video_player: ^2.1.12
  video_trimmer: ^0.5.4

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  chopper_generator: ^4.0.1
  flutter_launcher_icons: ^0.9.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mockito: ^5.0.14
  retrofit_generator: ^2.0.0+1

dependency_overrides: # autoroute
  args: 2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/findskill-launcher.png"
  adaptive_icon_foreground: "assets/png/findskill-launcher.png"
  adaptive_icon_background: "#ff8800"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets\png\findskill-logo-under-text.png

flutter:
  uses-material-design: true

  assets:
    - assets/png/onboarding-image.png
    - assets/png/findskill-logo.png
    - assets/png/findskill-logo-side-text-white.png
    - assets/png/jobseeker.png
    - assets/png/employer.png
    - assets/png/gallery.png
    - assets/png/findskill-logo-under-text.png
    - assets/png/findskill-logo-side-text.png
    - assets/png/whatsapp-icon.png
    - assets/video/Onboarding.mp4
    - assets/video/FindSkill-English-Intro.mp4
    - assets/video/FindSkill-Hindi-Intro.mp4
    - assets/video/FindSkill-English-Notice.mp4
    - assets/video/FindSkill-Hindi-Notice.mp4
    - assets/svg/findskill-appbar.svg
    - assets/svg/under-construction.svg
    - assets/language/en.json
